"""Local NanoMQ mTLS E2E checks.

The tests consume materials generated by scripts/prepare_nanomq_mtls.py. They
intentionally do not start NanoMQ themselves: the broker process is an external
runtime dependency, so these tests stay opt-in via RUN_NANOMQ_MTLS_E2E=1.

Design model:
- NanoMQ trusts the generated Root CA.
- The client sends device_chain.pem, which contains device leaf + intermediate.
- Positive coverage proves TLS handshake and MQTT publish/subscribe both work.
- Negative coverage proves missing, wrong, or incomplete client chains are rejected.
"""

import json
import os
import ssl
import time
from pathlib import Path
from queue import Empty, Queue
from threading import Event

import paho.mqtt.client as mqtt
import pytest

from utils.naming import unique_client_id, unique_topic


MANIFEST_PATH = Path(".tmp/nanomq-mtls/manifest.json")


pytestmark = [pytest.mark.e2e, pytest.mark.tls]


@pytest.fixture(scope="module")
def mtls_manifest():
    """Load generated certificate paths only when live mTLS tests are enabled."""
    # These tests require a real local NanoMQ process. Keep them opt-in so the
    # default suite remains offline and deterministic.
    if os.getenv("RUN_NANOMQ_MTLS_E2E") != "1":
        pytest.skip("Set RUN_NANOMQ_MTLS_E2E=1 to run local NanoMQ mTLS E2E tests.")
    if not MANIFEST_PATH.exists():
        pytest.fail(
            "NanoMQ mTLS manifest not found. Run "
            "`./venv/bin/python scripts/prepare_nanomq_mtls.py` first."
        )
    return json.loads(MANIFEST_PATH.read_text(encoding="utf-8"))


def test_valid_client_certificate_can_publish_and_subscribe(mtls_manifest):
    """A valid device certificate should establish mTLS and carry MQTT traffic."""
    certs = mtls_manifest["certificates"]
    topic = unique_topic("study/mtls")
    payload = "mtls-ok"
    received_messages: Queue[str] = Queue()

    # Both clients present the full device chain because NanoMQ is configured to
    # trust the root CA, not the intermediate directly.
    subscriber = _new_tls_client(
        mtls_manifest,
        client_id=unique_client_id("mtls-subscriber"),
        certfile=certs["device_chain"],
        keyfile=certs["device_key"],
    )
    publisher = _new_tls_client(
        mtls_manifest,
        client_id=unique_client_id("mtls-publisher"),
        certfile=certs["device_chain"],
        keyfile=certs["device_key"],
    )

    connected = Event()
    subscribed = Event()

    def on_connect(client, userdata, flags, reason_code, properties):
        if not reason_code.is_failure:
            connected.set()

    def on_subscribe(client, userdata, mid, reason_codes, properties):
        subscribed.set()

    def on_message(client, userdata, message):
        received_messages.put(message.payload.decode("utf-8"))

    subscriber.on_connect = on_connect
    subscriber.on_subscribe = on_subscribe
    subscriber.on_message = on_message

    try:
        subscriber.connect(mtls_manifest["host"], mtls_manifest["port"])
        subscriber.loop_start()
        assert connected.wait(5), "mTLS subscriber did not connect"

        result, _ = subscriber.subscribe(topic, qos=0)
        assert result == mqtt.MQTT_ERR_SUCCESS
        assert subscribed.wait(5), "mTLS subscriber did not subscribe"

        publisher.connect(mtls_manifest["host"], mtls_manifest["port"])
        publisher.loop_start()
        time.sleep(0.5)

        result = publisher.publish(topic, payload, qos=0)
        assert result.rc == mqtt.MQTT_ERR_SUCCESS

        assert _read_message(received_messages, timeout=5) == payload
    finally:
        _stop_client(publisher)
        _stop_client(subscriber)


def test_client_without_certificate_is_rejected(mtls_manifest):
    """fail_if_no_peer_cert=true should reject clients with no certificate."""
    client = _new_tls_client(
        mtls_manifest,
        client_id=unique_client_id("mtls-no-cert"),
        certfile=None,
        keyfile=None,
    )

    _assert_rejected(client, mtls_manifest)


def test_wrong_client_certificate_is_rejected(mtls_manifest):
    """A client certificate from an untrusted CA must not connect."""
    certs = mtls_manifest["certificates"]
    client = _new_tls_client(
        mtls_manifest,
        client_id=unique_client_id("mtls-wrong-cert"),
        certfile=certs["wrong_device_cert"],
        keyfile=certs["wrong_device_key"],
    )

    _assert_rejected(client, mtls_manifest)


def test_leaf_client_certificate_without_intermediate_chain_is_rejected(mtls_manifest):
    """A trusted root still needs the intermediate when the leaf is not direct."""
    certs = mtls_manifest["certificates"]
    # The leaf certificate is valid, but NanoMQ cannot build the chain to the
    # trusted root without the intermediate certificate.
    client = _new_tls_client(
        mtls_manifest,
        client_id=unique_client_id("mtls-missing-intermediate"),
        certfile=certs["device_cert"],
        keyfile=certs["device_key"],
    )

    _assert_rejected(client, mtls_manifest)


def _new_tls_client(
    mtls_manifest, *, client_id: str, certfile: str | None, keyfile: str | None
):
    """Create a paho client configured to verify NanoMQ and optionally present a cert."""
    certs = mtls_manifest["certificates"]
    client = mqtt.Client(
        callback_api_version=mqtt.CallbackAPIVersion.VERSION2,
        client_id=client_id,
        protocol=mqtt.MQTTv311,
    )
    client.tls_set(
        ca_certs=certs["root_ca"],
        certfile=certfile,
        keyfile=keyfile,
        tls_version=ssl.PROTOCOL_TLS_CLIENT,
    )
    client.tls_insecure_set(False)
    return client


def _assert_rejected(client, mtls_manifest) -> None:
    """Accept either TLS-handshake failure or immediate disconnect as rejection."""
    connected = Event()
    disconnected = Event()

    def on_connect(client, userdata, flags, reason_code, properties):
        if not reason_code.is_failure:
            connected.set()

    def on_disconnect(client, userdata, disconnect_flags, reason_code, properties):
        disconnected.set()

    client.on_connect = on_connect
    client.on_disconnect = on_disconnect

    try:
        # Rejection can happen either during TLS handshake or immediately after
        # MQTT starts processing the failed TLS session.
        try:
            client.connect(mtls_manifest["host"], mtls_manifest["port"])
        except (OSError, ssl.SSLError):
            return

        client.loop_start()
        disconnected.wait(5)
        assert not connected.is_set(), "mTLS client connected but should be rejected"
    finally:
        _stop_client(client)


def _read_message(messages: Queue[str], timeout: float) -> str:
    """Poll the callback queue because paho receives messages asynchronously."""
    deadline = time.monotonic() + timeout
    while time.monotonic() < deadline:
        try:
            return messages.get_nowait()
        except Empty:
            time.sleep(0.1)
    raise AssertionError("Timed out waiting for MQTT message")


def _stop_client(client) -> None:
    """Best-effort cleanup for clients that may not have fully connected."""
    try:
        client.loop_stop()
    finally:
        client.disconnect()
